spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: test
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  flyway:

    baseline-on-migrate: true
    locations: classpath:/db
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    rest:
      base-path: /api

